require "opencl_ruby_ffi/opencl_ruby_ffi_base_gen.rb"
require "opencl_ruby_ffi/opencl_ruby_ffi_base.rb"
require "opencl_ruby_ffi/Arithmetic_gen.rb"
require "opencl_ruby_ffi/Context.rb"
require "opencl_ruby_ffi/Platform.rb"
require "opencl_ruby_ffi/Device.rb"
require "opencl_ruby_ffi/CommandQueue.rb"
require "opencl_ruby_ffi/Mem.rb"
require "opencl_ruby_ffi/Buffer.rb"
require "opencl_ruby_ffi/Program.rb"
require "opencl_ruby_ffi/Event.rb"
require "opencl_ruby_ffi/Kernel.rb"
require "opencl_ruby_ffi/Image.rb"
require "opencl_ruby_ffi/Sampler.rb"
require "opencl_ruby_ffi/Pipe.rb"
require "opencl_ruby_ffi/SVM.rb"

require "narray_ffi"


