using OpenCLRefinements if RUBY_VERSION.scan(/\d+/).collect(&:to_i).first >= 2

module OpenCL
  CONTEXT_DRIVER_DIAGNOSTICS_INTEL = 0x4106
  CONTEXT_SHOW_DIAGNOSTICS_INTEL = 0x4106
  CONTEXT_DIAGNOSTICS_LEVEL_GOOD_INTEL = 0x1
  CONTEXT_DIAGNOSTICS_LEVEL_BAD_INTEL = 0x2
  CONTEXT_DIAGNOSTICS_LEVEL_NEUTRAL_INTEL = 0x4

  class Context
    DRIVER_DIAGNOSTICS_INTEL = 0x4106
    SHOW_DIAGNOSTICS_INTEL = 0x4106
    DIAGNOSTICS_LEVEL_GOOD_INTEL = 0x1
    DIAGNOSTICS_LEVEL_BAD_INTEL = 0x2
    DIAGNOSTICS_LEVEL_NEUTRAL_INTEL = 0x4
    
  end

end
